### PR TITLE
Improve tests suite

### PR DESCRIPTION
**Pull request by alexjab**
Hi,

I thought the test suite needed a little upgrade; I threw in test coverage using Istanbul, I tested some more error cases, and a couple of small things hither and yon.

I hope it will suit the project, any feedback will be appreciated =)

### CODE REVIEW

**Comment by hokaccha** [comment]
Looks great, but CI is failed :(

That's because testing versions are very old.
https://github.com/hokaccha/node-jwt-simple/blob/master/.travis.yml#L3-L5

I think we don't have to support v0.8 or less versions and should support v4.0, v5.0. Could you also update the `.travis.yml`?

**Comment by alexjab** [comment]
Sounds good to me, you'll have it as soon as I'm finished with my meeting =)

On Thursday, 21 January 2016, Kazuhito Hokamura <notifications@github.com>
wrote:

> Looks great, but CI is failed :(
>
> That's because testing versions are very old.
> https://github.com/hokaccha/node-jwt-simple/blob/master/.travis.yml#L3-L5
>
> I think we don't have to support v0.8 or less versions and should support
> v4.0, v5.0. Could you also update the .travis.yml?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hokaccha/node-jwt-simple/pull/34#issuecomment-173617334>
> .
>


-- 
Alexandre Jablon

http://jablon.me <http://alex.jablon.me>
alex@jablon.me

**Comment by alexjab** [comment]
I also took the liberty to pin the versions of devDependencies, I think it's better this way.

**Comment by alexjab** [comment]
Up.

**Comment by alexjab** [comment]
I've just noticed in the expect.js documentation that `throwError` expects a regular expression as parameter and not a string; that does not make much sense to me, but I ought to fix it my tests anyway.

**Comment by hokaccha** [comment]
> I also took the liberty to pin the versions of devDependencies, I think it's better this way.

:+1: 

> I've just noticed in the expect.js documentation that throwError expects a regular expression as parameter and not a string; that does not make much sense to me, but I ought to fix it my tests anyway.

:+1: :+1: 

LGTM :+1:

**Pull request merged**
