### PR TITLE
added try catch around parsing header and payload

### PR DESCRIPTION
**Pull request by joshterrill**
Added error handling if the library cannot JSON parse the base64 that is coming into the header and payload.

### CODE REVIEW

**Comment by alexjab** [comment]
Hi,

I not sure I see the added value of your proposal, since you're basically just catching an error to throw it right after, so I don't think I'm going to merge this.

Here are a couple of remarks about what you wrote:
 - I don't think you should call the caught error `ex`, this is not Python,
 - I don't think you should put punctuation marks (such as `-`) in your error messages, they should be as plain as possible,
 - `JSON.parse` actually throws a `SyntaxError`, so you could technically do `if (error instanceof SyntaxError)`, should you need to know what error was thrown,
 - you did not provide any test case for your changes, nor any documentation. That is usually a red flag when contributing to any project.

BR,

Alex

**Comment by hokaccha** [comment]
I completely agree with @alexjab

**Comment by hokaccha** [comment]
@joshterrill This patch will not be merged, but I appreciate your work.

@alexjab Can you close this PR? I'd like to confirm your permission.

**Comment by alexjab** [comment]
@hokaccha Done. I'll try to do a bit of spring cleaning.

**Pull request closed without merging**
